version: "2"

services:
  java:
    container_name: springapp
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
        #    networks:
        #      - webnet

        #networks:
        #  webnet:

